"""Markdown report exporter."""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from api_relay_audit.engine.result import AuditResult, DetectorResult, RiskLevel
from api_relay_audit.engine.result import TestCase

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)

RISK_EMOJI = {
    RiskLevel.LOW: "✅",
    RiskLevel.MEDIUM: "⚠️",
    RiskLevel.HIGH: "🔴",
    RiskLevel.CRITICAL: "💀",
}


class MarkdownExporter:
    """Exports AuditResult to a readable Markdown report."""

    def export(self, audit_result: AuditResult, output_path: Path) -> None:
        """Export an audit result to a Markdown file.

        Args:
            audit_result: The audit result to export.
            output_path: Path to write the Markdown file.
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        md = self._build_report(audit_result)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(md)

        logger.info(f"Markdown report written to {output_path}")

    def _build_report(self, result: AuditResult) -> str:
        """Build the full Markdown report."""
        lines: list[str] = []
        score = result.metadata.get("score", 0)
        overall_emoji = RISK_EMOJI.get(result.overall_risk, "❓")

        lines.append("# API Relay Security Audit Report\n")
        lines.append(f"**Generated**: {self._format_timestamp(result.timestamp)}")
        lines.append(f"**Target**: `{result.target_url}`")
        if result.target_name:
            lines.append(f"**Target Name**: {result.target_name}")
        lines.append(f"**Model**: `{result.model}`")
        lines.append(f"**Detected Format**: {self._format_label(result.detected_format)}")
        lines.append(f"**Duration**: {result.duration_seconds:.1f}s")
        lines.append(f"**Overall Risk**: {overall_emoji} **{result.overall_risk.value.upper()}**\n")
        lines.append("---\n")

        # Risk breakdown table
        lines.append("## Risk Breakdown\n")
        lines.append("| Detector | Risk Level | Score |")
        lines.append("|----------|-------------|-------|")
        for dr in result.detector_results:
            emoji = RISK_EMOJI.get(dr.risk_level, "?")
            s = result.metadata.get("score", 0)
            lines.append(
                f"| {dr.detector_id} | {emoji} {dr.risk_level.value.upper()} | "
                f"{self._detector_score(dr)} |"
            )
        lines.append(f"\n**Overall Score**: {score} / 100\n")
        lines.append("---\n")

        # Per-detector sections
        for dr in result.detector_results:
            self._write_detector_section(lines, dr)

        lines.append("\n---\n")
        lines.append(f"*Report generated by api-relay-audit v1.0.0*\n")

        return "\n".join(lines)

    def _write_detector_section(self, lines: list[str], dr: DetectorResult) -> None:
        """Write a section for a single detector."""
        emoji = RISK_EMOJI.get(dr.risk_level, "?")
        lines.append(f"## {dr.detector_id.replace('_', ' ').title()}\n")
        lines.append(f"**Status**: {emoji} {dr.risk_level.value.upper()} — {dr.summary}\n")
        lines.append(f"\n{dr.description}\n" if hasattr(dr, "description") else "")

        if dr.findings:
            lines.append("| Test | Input Tokens | Output Tokens | Passed |")
            lines.append("|------|-------------|---------------|--------|")
            for tc in dr.findings:
                status = "✅" if tc.passed else "❌"
                lines.append(
                    f"| {tc.name} | {tc.input_tokens} | {tc.output_tokens} | {status} |"
                )
            lines.append("")

        if dr.raw_data:
            lines.append("**Raw Data**:\n")
            for key, value in dr.raw_data.items():
                lines.append(f"- `{key}`: {value}")
            lines.append("")

        lines.append("---\n")

    def _detector_score(self, dr: DetectorResult) -> int:
        score_map = {
            RiskLevel.LOW: 10,
            RiskLevel.MEDIUM: 45,
            RiskLevel.HIGH: 80,
            RiskLevel.CRITICAL: 100,
        }
        return score_map.get(dr.risk_level, 0)

    def _format_timestamp(self, ts: str) -> str:
        try:
            dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
            return dt.strftime("%Y-%m-%d %H:%M UTC")
        except Exception:
            return ts

    def _format_label(self, fmt: str) -> str:
        labels = {"openai": "OpenAI-compatible", "anthropic": "Anthropic-compatible", "auto": "Auto-detected", "unknown": "Unknown"}
        return labels.get(fmt, fmt)
